<?php
define("CLIENT_ID","AUUcnthmX-V_ce1T0gYK4jsmHKizhw4Edvx6yzNOoxvgxMZgTxmpFJUIK0dlVgmJxTauxDskUCub1G2W");
define("CLIENT_SECRET","EAHrM7rlEUt8G5pnWdMA7PS4acsWu3tFBaG4IgBvsZBNWUiepg6FQj15qFTvRID6jJYOg4OBZeBbjanv");